// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateUserInput struct {
	UUID      string `json:"uuid"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type Exercise struct {
	UUID              string `json:"uuid"`
	Name              string `json:"name"`
	DurationInSeconds int    `json:"durationInSeconds"`
}

type ExercisePerformance struct {
	UUID                   string    `json:"uuid"`
	User                   *User     `json:"user"`
	Exercise               *Exercise `json:"exercise"`
	RepTimestampsInSeconds []*int    `json:"repTimestampsInSeconds"`
}

type Friendship struct {
	FriendA *User `json:"friendA"`
	FriendB *User `json:"friendB"`
}

type GroupWorkout struct {
	UUID                string                `json:"uuid"`
	Workout             *Workout              `json:"workout"`
	WorkoutPerformances []*WorkoutPerformance `json:"workoutPerformances"`
}

type UpdateUserInput struct {
	UUID      string  `json:"uuid"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
}

type User struct {
	UUID      string        `json:"uuid"`
	FirstName string        `json:"firstName"`
	LastName  string        `json:"lastName"`
	PhotoURI  *string       `json:"photoURI"`
	Friends   []*Friendship `json:"friends"`
}

type Workout struct {
	UUID      string      `json:"uuid"`
	Name      string      `json:"name"`
	PhotoURI  string      `json:"photoURI"`
	Exercises []*Exercise `json:"exercises"`
}

type WorkoutPerformance struct {
	UUID                 string                 `json:"uuid"`
	User                 *User                  `json:"user"`
	Workout              *Workout               `json:"workout"`
	ExercisePerformances []*ExercisePerformance `json:"exercisePerformances"`
}
