// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateUserInput struct {
	UUID      string `json:"uuid"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type UpdateUserInput struct {
	UUID      string  `json:"uuid"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
}

type User struct {
	UUID      string  `json:"uuid"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	PhotoURI  *string `json:"photoURI"`
}
